# Generated by Django 3.0.1 on 2019-12-22 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='mobile_number',
            field=models.PositiveIntegerField(unique=True, verbose_name='Mobile Number'),
        ),
    ]
