# Generated by Django 3.0.1 on 2019-12-22 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_balance', models.FloatField(blank=True, default=0, verbose_name='Total Balance')),
                ('total_due', models.FloatField(blank=True, default=0, verbose_name='Total Due')),
                ('ac_active', models.BooleanField(default=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clients.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(default='', max_length=100, verbose_name='Package')),
                ('package_bill', models.FloatField(default=0, verbose_name='Per Month Amount')),
                ('month_cycle', models.IntegerField(default=30, verbose_name='Month Cycle')),
                ('per_day_amount', models.FloatField(blank=True, null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AccountPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_date', models.DateField(editable=False, verbose_name='Opening Date')),
                ('closed_date', models.DateField(blank=True, editable=False, null=True, verbose_name='Closed Date')),
                ('balance', models.FloatField(blank=True, default=0, verbose_name='Total Balance')),
                ('due', models.FloatField(blank=True, default=0, verbose_name='Total Due')),
                ('ac_status', models.BooleanField(default=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Account')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Package')),
            ],
        ),
    ]
