# Generated by Django 3.0.1 on 2019-12-22 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountpackage',
            old_name='account',
            new_name='account_holder',
        ),
    ]
