# Generated by Django 3.0.1 on 2019-12-22 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20191222_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountpackage',
            name='active_date',
            field=models.DateField(verbose_name='Opening Date'),
        ),
        migrations.AlterField(
            model_name='accountpackage',
            name='closed_date',
            field=models.DateField(blank=True, null=True, verbose_name='Closed Date'),
        ),
    ]
