# Generated by Django 3.0.1 on 2019-12-22 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20191222_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountpackage',
            name='total_days',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
